### ISSUE TITLE
Suggestion: Enable cookies in private mode and Don't ask on exit

### ISSUE THREAD

**Issue by bastadur** [hazuki0x0/YuzuBrowser#1]
Hey, just started using your browser and I love it. Just two suggestions for you are to add an option to enable cookies with the private mode and an option to disable prompt (clear this and that) on exit. 

The level of customizing options is amazing. Keep up the good work!

**Comment by hazuki0x0** [comment]
I added a setting to enable cookies in private mode!
if you want to disable prompt, you can use "Show alert" option in "finish" action.
