### ISSUE TITLE
Support Blob download format

### ISSUE THREAD

**Issue by rancidfrog** [hazuki0x0/YuzuBrowser#106]
No support to download via blob uri
pdf represented by blob link fails:
![](https://i.imgur.com/26zqs6d.png)

I.E.
- https://stackoverflow.com/questions/52283258/download-pdf-file-from-blob-url-inside-androids-webview
- https://developers.google.com/web/updates/2011/08/Downloading-resources-in-HTML5-a-download

**Comment by hazuki0x0** [comment]
It supported. However,some site cannot download blob format due to same-origin policy (60254da42c2cadf34f45a95f194dc323a78b265e).

**Comment by rancidfrog** [comment]
Thank you
