### ISSUE TITLE
Make browser remember formdata (passwords)

### ISSUE THREAD

**Issue by WinDanesz** [hazuki0x0/YuzuBrowser#111]
Hello,
Not sure if this feature is already implemented and I just couldn't find it yet, but I'd like to make the browser remember (then autofill) login credentials informs for a few websites. It does remember usernames for a few sites, where I can select it from a dropdown, but I cant make it remember the password.
Thanks in advance!

Ps.: the hungarian translation will soon be finished in Zanata.

**Comment by meDevil** [comment]
setting~private settings~clean data at finish

**Comment by WinDaniel** [comment]
Hi. How does this function solve the problem? I tried toggling it, still I can't autofill the user/pw. I does not use the Finish function (close browser & clean data when i finish browsing). I just switch between apps, then the session is interrupted and I have to type in my credentials again.

**Comment by hazuki0x0** [comment]
Fixed Autofill not working with Oreo def90e19a752d80e4509b2d55f6fc3c100aa0f21
