### ISSUE TITLE
Bug: Actively refreshing the page should renew cached version

### ISSUE THREAD

**Issue by source124** [hazuki0x0/YuzuBrowser#12]
**Steps to reproduce**:
1. Load cache preferentially (Settings > Privacy Settings > Cache mode).
2. Load any web page.
3. Press refresh OR
    Tap the link to the webpage from bookmarks or SpeedDial OR
    Re-type the URL manually.

**Actual behavior**:
            - Page is reloaded from cache.

**Expected Behavior**:
            - Actively seeking a new version of the page should signal that the user want to "refresh" the content of the page. Cached version should be used otherwise, as in pressing Back and Forward arrows and tab history navigation.

**Comment by hazuki0x0** [comment]
May be WebView bug or specification.
Detailed operation is unknown because it is a black box.
However, on the browser side, it is set simultaneously with other settings.

**Comment by source124** [comment]
OK. Maybe (under Default cache mode) automatically load cached version when there is no network connection?

Thanks

**Comment by hazuki0x0** [comment]
I don't know this WebView cache behavior, but alert "no network connection error" at such times.

**Comment by source124** [comment]
Sorry, I didn't make myself clear enough :) I meant this as a suggestion.

As a part of the default cache mode in the browser: if there is no internet connection, I suggest the app show the cached version of the page instead of just showing the WebView "Web page not available" error.

Thanks :)
