### ISSUE TITLE
Version 5.0.0 Beta1 doesn't launch.

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#128]
Hi,

Xperia X, stock Oreo 8.0.1, the latest Version 5.0.0 Beta1 doesn't launch at all.

**Comment by hazuki0x0** [comment]
Sorry, there is no information to identify the cause.
Could you send settings backup for me?
You can open the settings by long tapping the browser icon.

**Comment by ksuuk** [comment]
@hazuki0x0 

I had 4.2.3 installed, upgraded to 5.0 via Google Play. Noticed, that during upgrade, from launcher Yuzu shortcut was deleted. After upgrade, Yuzu din't launch. So I deleted app data, Yuzu launched, imported bookmarks, speed dial, and finally settings and again, Yuzu 5.0.0. beta1/beta2 doesn't launch at all. 

And as backup contains a lot sensitive information, I don't wan't to share it. :(

**Comment by hazuki0x0** [comment]
Thank you for uploading the log!
It looks like a bug when the DayNight theme restarts an activity. (May be)
I tried to suppress the restart of activity with 16cd80aced22d166c657aa13d086d3994aa42666.

**Comment by ksuuk** [comment]
@hazuki0x0 

Somehow I already got also Beta2 working, launch yuzu = crash, open yuzu settings, launch yuzu = crash (about 10 times so), open yuzu settings > app settings > disable kill process on exit, launch yuzu = success. Then later when I cleaned app cache (via app management), I had again launch yuzu about 10 times and finally succeeded. Beta 3 upgrade wen't fine, all OK now.

Thanks!

**Comment by hazuki0x0** [comment]
Thank you for debugging and repoting!
I remove "kill process on exit" option now.
