### ISSUE TITLE
Upgrade to a more formal privacy policy.

### ISSUE THREAD

**Issue by HarryHeights** [hazuki0x0/YuzuBrowser#135]
Hi, I'm Harry. I recently stumbled on this project. It's a cool browser to use. Especially with the customizations and stuff. I checked out your privacy policy but, it wasn't really up to par for an amazing app such as this, especially for a browser. It would great if it was a little more formal and organized. I can help with that so you don't have to worry.
I just wanna know your thoughts about it.

Thanks.

**Comment by hazuki0x0** [comment]
Hi, Harry.
I don't know how to write a formal privacy policy and I am not good at English. So, I wrote simple privacy policy.
I wrote additional information about Fabric just now.
I hope for your cooperation.

**Comment by HarryHeights** [comment]
No problem @hazuki0x0 . I will create a more formal privacy policy for you. But, I don't know how I'll make changes to the already existing policy on the wiki. What I'll do is; send a PR then you can transfer it to the wiki or just merge it anyway.
By the way, I also wanted to inquire if there's anyway you can collect user data?

**Comment by hazuki0x0** [comment]
OK, please send a PR of privacy-policy.md or something similar.
I can collect user data, but I only collect crash logs and application health(number of users for calculating the number of crash free users).

**Comment by HarryHeights** [comment]
Okay. Thanks for the information. I'll work on the content and send a PR soon.
