### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by RainbowStarX** [hazuki0x0/YuzuBrowser#14]
Hello, Hazuki !
This is a great browser and i like it very much, but there is a very critical option please consider adding to "Pattern Match" 
Cookies Disabled/Enabled

Thanks for making such a great browser ..!

**Comment by mp107** [comment]
I agree.

And a suggestion of an enhancement of it:
It might be useful to to add a general option to make all cookies session only (=clean up them on browser closure) and second - for some particular websites (in "Pattern match" section) - to enable only first party cookies.
That way we would be able to keep being logged in for some particular websites (f.e. forums) and to do not be tracked using cookies by any third parties (Facebook, Google, ad companies, etc.).
That is the way I set up my desktop browser.
