### ISSUE TITLE
Hide ad-blocked elements

### ISSUE THREAD

**Issue by FluffyDiscord** [hazuki0x0/YuzuBrowser#147]
Hi, while it takes a sec to go through 1mb backlist and blocks ads, it does not however hide blocked elements. Do you think you could implement something that will hide blocked dom elements?

**Comment by meDevil** [comment]
u can use Greasemonkey user-script 2 do that.
// ==UserScript==
// @name   Mark Ads
// @namespace    None
// @version    0.1
// @description    分域名标记广告
// @author    Anonymous
// @include    *
// @grant    none
// ==/UserScript==

function clearAds(elm, array_url) {
    var isUrl = false;
    for (var x = 0; x < array_url.length; x++) {
        if (location.href.match(array_url[x])) {
            isUrl = true;
        };
    };
    if (isUrl) {
        var head = document.getElementsByTagName('head')[0];
        var myStyle = document.createElement('style');
        myStyle.type = "text/css";
        myStyle.innerHTML = elm + "{display:none !important;visibility:hidden !important;width:0 !important;height:0 !important;}";
        head.appendChild(myStyle);
    };
};
clearAds("#loading", ["pl.win007.com"]);
//clearAds(".header,.footer,.song-comment,.print-btn,.tip,.accompany-item,.backtotop-btn,.tomusic-btn.show", ["happi123.com"]);
clearAds(".appTips,aside.tips", ["weibo.cn"]);
clearAds(".index__openBtn__src-commonComponent-openBtn-,.index__openAppBtn__src-commonComponent-topArea-,.index__openAppBtn__src-videoPage-openAppBtn-,.index__downLoadBtn__src-videoPage-commentArea-", ["bilibili.com"]);
clearAds("div#index-card>div:last-child,.baiduapp-ad-body", ["m.baidu.com", "www.baidu.com"]);
clearAds(".scroll-content>div[dpr]", ["taobao.com"]);
clearAds("div[data-stat-role],div#banner,div[sourcetype],div[data-spm]", ["youku.com"]);
clearAds("div[data-node],div.header-app,div.m-box-items[data-component],div.iqy-items[glue-component='page.home.fragment.focusMap'],[glue-node=ad]", ["iqiyi.com"]);
clearAds("div.topfr,div.ftwrap,div.footer-wrap,div.u-footer", ["music.163.com"]);
clearAds("div.download-app,div.js-downloadApp,div.download-box", ["m.kugou.com"]);
clearAds("div.download,div.open_app,div.topAppWrap", ["m.kuwo.cn"]);
clearAds(".btn_download,div.top_bar", ["y.qq.com"]);
clearAds("#tip-download,.btn-download,.not-in-live>p,.download", ["m.panda.tv"]);
clearAds(".h5_footer,.app_open,div.gift_block", ["chushou.tv"]);
clearAds(".u-btn-down,#globalRightSide", ["m.huya.com"]);
clearAds("#js-fix-download,.btn-open-app,.download,.layout-ball,div.get-gift-box", ["m.douyu.com"]);
clearAds(".scroll-download,div[data-cate=zhaomu],[data-label=h5-dw-app],[data-label=topbar-login],.footer-item-1", ["m.longzhu.com"]);
clearAds(".MobileAppHeader-downloadLink,.OpenInApp,.OpenInAppButton", ["zhihu.com"]);
clearAds("div.download.clearfix,div.download-box,div.order-box", ["yinyuetai.com"]);

**Comment by FluffyDiscord** [comment]
This seems rather simple, I will try to write some sort of a script to add all pages/elements I want to hide and test performance, I guess its gonna tank like hell.

**Comment by hazuki0x0** [comment]
I'm working on ad block and it will be implemented in the next feature release.

**Comment by meDevil** [comment]
@hazuki0x0     support Adblock Plus filtering files？

**Comment by grant** [comment]
Please use \`\`\` to escape code that includes `@grant`.

**Comment by hazuki0x0** [comment]
@meDevil Yes, It'll be able to manage Adblock Plus filter.

**Comment by NiceFeather** [comment]
Yes, removing ad-blocked elements is very important, otherwise it will leave a large number of blank areas in the web page.

**Comment by meDevil** [comment]
any way to edit the filters at yuzu://adblock/filter
@hazuki0x0

**Comment by FluffyDiscord** [comment]
Adblock lists doesn't work (?). When I turn it on and add some easylists, I still see ads. Anything special I need to do?

**Comment by NiceFeather** [comment]
Yes, I just did certain test, those already exists rules not working after appending new adblock plus filters.

**Comment by meDevil** [comment]
when select just one filter file, it works. when select several or all filter files it doesn't.

**Comment by FluffyDiscord** [comment]
Heureka! Beta2 1.6.2019 and filters work! Fuc**ing sweet! Now we have the fastest browser with fully working adblock which does not slow pade loading down. Incredible work
