### ISSUE TITLE
Browser crashes in version 3.3.0 in Pattern Match

### ISSUE THREAD

**Issue by medwatt** [hazuki0x0/YuzuBrowser#15]
Going to Settings > Browser Settings > Pattern Match and selecting any of the blue tabs (such as change web settings) will cause the browser to crash.

Also, enabling "load images" in one of the patterns doesn't stick. It reverts back to being disabled when you go back.

This is only the case on version 3.3.0. It wasn't the case in version 3.2.4.

I'm running Android 7.0.

**Comment by hazuki0x0** [comment]
fixed in 578d1d2 and 7eebde5
