### ISSUE TITLE
IMG files download error

### ISSUE THREAD

**Issue by rancidfrog** [hazuki0x0/YuzuBrowser#151]
I am trying to download twrp img file, buy Yuzu keeps downloading html file instead.

App reports the right file size:
![](https://i.imgur.com/MjnlLX8.png)

But actual file size is different:
![](https://i.imgur.com/80QRJr6.png)

And, it is actually downloading html file and not img:
![](https://i.imgur.com/3r3vbBV.png)

**Comment by rancidfrog** [comment]
Problem with referer,
none of my browsers would download img 
Finally was able to download with curl:
```
curl -e https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img.html  -L  -O https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img
```

**Comment by hazuki0x0** [comment]
Thank you for debugging!
