### ISSUE TITLE
Bookmarks clicking not working

### ISSUE THREAD

**Issue by NiceFeather** [hazuki0x0/YuzuBrowser#152]
In the latest released, I found the bookmarks clicking not working, would you fix this bug ASAP please? @hazuki0x0

**Comment by meDevil** [comment]
the adblock filter does not effect either, the new version is buggy, haha!

**Comment by meDevil** [comment]
Clicking history is not working either.

**Comment by meDevil** [comment]
Search engine switching does'nt work either.

**Comment by ksuuk** [comment]
@hazuki0x0 

Please reply, shall we downgrade or wait (how long) for the fix?
