### ISSUE TITLE
Ad block filters dupulicate

### ISSUE THREAD

**Issue by quroe** [hazuki0x0/YuzuBrowser#153]
## Short description
初期登録の広告ブロックフィルタが2重登録されている
## Steps to reproduce
 1. Yuzu Browserの設定を開き、ストレージ＞データを消去 で初期状態にする
 2. Yuzu Browserを起動
 3. 設定＞ブラウザ設定＞広告ブロック設定 を開き、広告ブロックを有効 のスイッチをオンにする
 4. 広告ブロックフィルタ を開くとフィルタが2重に登録されている
なお、アップデートによりデータを引き継いだ環境では再現せず正常にフィルタが登録されていた
## Expected result
```
Yuzu filter
EasyList
AdGuard Base filter
AdGuard Mobile Ads filter
```
の4つが表示される
## Actual result
```
Yuzu filter
EasyList
AdGuard Base filter
AdGuard Mobile Ads filter
Yuzu filter
EasyList
AdGuard Base filter
AdGuard Mobile Ads filter
```
の8つが表示される
## Environment
 * Platform (OS): Android7.0 Nougat
 * Model: Huawei nova2 HWV31
 * Version: Yuzu Browser 5.1.0-beta1

**Comment by meDevil** [comment]
The block filter doesn't seem to work

**Comment by quroe** [comment]
> 
> 
> The block filter doesn't seem to work

In addition to this...if block filter enable,Yuzu filter(blacklist) doesn't work.
I checked EasyList & Yuzu filter.

BTW,filter (not working) issue may open new issue for other user.

**Comment by meDevil** [comment]
Thank you, i got it.when select just one filter file, it works. when select several or all filter files it doesn't work.

**Comment by hazuki0x0** [comment]
Fixed
