### ISSUE TITLE
Edit query URL/intent dosn't working

### ISSUE THREAD

**Issue by quroe** [hazuki0x0/YuzuBrowser#156]
## Short description
Activity設定のクエリURLの編集およびインテントの編集をしても変更されない
## Steps to reproduce
 1. Yuzu Browserを起動し 設定＞操作設定＞メインメニュー設定 へ移動する
 2. フローティングボタンをタップし Activityを開く にチェックを入れる
 3. ページの共有 をタップし、適当なアプリを選択する(テストではAndmade Shareを用いた)
```
https://play.google.com/store/apps/details?id=com.andmadesoft.share
https://apkpure.com/jp/andmade-share/com.andmadesoft.share
```
 4. 歯車マークをタップし Activity設定 へ移動
 5. 3ドットメニューをタップし クエリURLの編集 か インテントの編集 で適当な文字列を入力する
 6. 3ドットメニューから JSON文字列を表示 で確認をすると変更が破棄されている
ちなみにJSON文字列を表示から編集を行った場合、正常に動作する事が確認できた
## Expected result
変更されたインテント/クエリURLがActivityに反映されている
## Actual result
クエリURLの編集 および インテントの編集 の設定値が反映されない
## Environment
 * Platform (OS): Android7.0 Nougat
 * Model: Huawei nova2 HWV31
 * Version: Yuzu Browser 5.1.0-beta2

**Comment by hazuki0x0** [comment]
修正しました．ただし，クエリURLはIntent候補呼び出し用のため，保存しない仕様です．
