### ISSUE TITLE
Is Safebrowsing limited to Oreo?

### ISSUE THREAD

**Issue by taka-hkd** [hazuki0x0/YuzuBrowser#16]
In your app, Android 8.0 or greater is required to enable GoogleSafebrowsing although Google says "5.0 and above". Why?

> Because WebView is distributed as a separate APK, Safe Browsing for WebView is available today for devices running Android 5.0 and above. With just one added line in your manifest, you can update your app and improve security for most of your users immediately.

Source written in English:
https://android-developers.googleblog.com/2017/06/whats-new-in-webview-security.html
Source written in Japanese:
https://developers-jp.googleblog.com/2017/07/whats-new-in-webview-security.html

**Comment by taka-hkd** [comment]
By the way, thanks for the good app!

**Comment by taka-hkd** [comment]
I think it would be better to enabling it and writing "Can't be disabled on 7.9 or below due to the restriction of older Android API". I can't tell exactly, but I don't think it's heavy because most browsers such as Chrome, Firefox and Opera enable it by default.

Let's wait until others comment on this thread. Thank you for the reply.

**Comment by hazuki0x0** [comment]
I'll test the change in beta.
