### ISSUE TITLE
Sorting bookmarks not working

### ISSUE THREAD

**Issue by DrStrange** [hazuki0x0/YuzuBrowser#171]
Select sort, get message "lets sort". Bookmarks aren't sorted.
Select sort again, get message "sorting complete!". Bookmarks still aren't sorted.
Using 5.1.0-beta4

**Comment by Rikk** [comment]
Did you long-press and drag the bookmark you wanted to move?

**Comment by DrStrange** [comment]
I tried long press on a bookmark. That highlights and selects that bookmark only but doesnt allow all the bookmarks to be sorted. In my first post when I click the three dots at the top right and get a flyout menu with Sort, Breadcrumbs and Simple display then click sort, the bookmarks are not sorted. I know I can click the three dots beside each bookmark and move them up or down from the menu that opens.

**Comment by Rikk** [comment]
"Sort" means you can drag a bookmark to a new position, not that bookmarks will be automatically sorted. So, first you click the Sort button, then you can long-press and drag one bookmark at a time.

**Comment by DrStrange** [comment]
Ok, Thanks for clearing up my confusion. I have closed this issue.
