### ISSUE TITLE
Changing useragent not working

### ISSUE THREAD

**Issue by didux70** [hazuki0x0/YuzuBrowser#181]
Changing useragent in settings does not have any effect in latest beta! For example, when you want to view a website in "desktop mode (PC)" there is no difference.

**Comment by mp107** [comment]
@didux70 Website may use also another ways to determine whether it is accessed using a mobile device.
Are you sure the "User-Agent" HTTP header is not set properly?
You can check it for example [here](https://duckduckgo.com/?q=user+agent&t=lm&ia=answer).

**Comment by didux70** [comment]
@mp107 Thank you, according to your link, changing useragent is handled correctly by Yuzu Browser! These websites I visited in "desktop mode", in order to make them "readable", must have changed something, so they are not displayed as before!? *SOLVED*
