### ISSUE TITLE
[Bug] Navbar Back button doesn't work in setting

### ISSUE THREAD

**Issue by quroe** [hazuki0x0/YuzuBrowser#188]
**Describe the bug**
いくつかの設定ページで、ナビゲーションバー上のバックキーを押してもYuzu Browserが前の画面に戻らない

**To Reproduce**
1. `履歴`または`ダウンロード一覧`を開く
2. ナビゲーションバーのバックボタンをタップ

**Expected behavior**
直前に開いていたWebページへ戻る

**Device information (please complete the following information):**
 - Device: HUAWEI nova 2
 - OS: Android 7.0
 - Browser version: Yuzu Browser 6.0.0-nightly

**Additional context**
上記設定画面の左上にある`←`アイコンのタップは動作し、直前のページに戻ることができます

**Comment by hazuki0x0** [comment]
すでに 3b51ab2cff5b3bd1acd5599c342cfa2aea68d8d2 で修正はしたので，次のビルドで治るはずです．

**Comment by quroe** [comment]
申し訳ない、Commits見落としてました
対応ありがとうございました！
