### ISSUE TITLE
Can't close the last tab in tab list

### ISSUE THREAD

**Issue by erik0200** [hazuki0x0/YuzuBrowser#19]
When it remains one tab left in tab list, I can't close that tab by pressing X or swiping up. Are there any options can make it? 
Thanks for your patience, I love this awesome browser.  d(  >∀･)b

**Comment by hazuki0x0** [comment]
The option has been committed at 5b3d527e2cbd7bf4103d9fd6520e5f5a7ce8c38f.
Please wait for next feature update.

**Comment by erik0200** [comment]
Thank you. :)

**Comment by zelleb** [comment]
Is this implemented in the latest version?
I can't find it.

Would someone be so kind and tell me where I can set this option?

**Comment by hazuki0x0** [comment]
This option available in [Tab list] action's option.
ex.)Action settings→Software button settings→Custom button→[Tab list]→press→option[gear icon]

**Comment by zelleb** [comment]
Thanks! That feels way better than before!

**Comment by erik0200** [comment]
It seems not working on another type of  tab list which is with preview window.
