### ISSUE TITLE
Any file download crashes Yuzu v6

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#190]
Xperia X, stock Oreo 8.0

1. Go to https://github.com/Hazuki0x0/YuzuBrowser/releases
2. Click on https://github.com/hazuki0x0/YuzuBrowser/releases/download/nightly_20210215/jp.hazuki.yuzubrowser_v6.0.0-nightly_410015.apk
3. Yuzu v6 (tested with both versions) does not download anything and crashes and this happens always anywhere with any file type.

Screenshots added.

![Screenshot 2021-02-15 at 17 44 33](https://user-images.githubusercontent.com/26193002/107967531-eb289080-6fb5-11eb-8fe7-1f6cacf70180.png)

![Screenshot 2021-02-15 at 17 44 58](https://user-images.githubusercontent.com/26193002/107967549-ef54ae00-6fb5-11eb-842e-6d0c8a306999.png)

**Comment by quroe** [comment]
Additional Info.

**Device information:**
 - Device: HUAWEI nova 2
 - OS: Android 7
 - Browser version: 6.0.0 nightly 20210215
Yuzu Browser can download apk.
HUAWEI's EMUI is far from AOSP.

**Device information:**
 - Device: HTC HTL23
 - OS: Android 6
 - Browser version: 6.0.0 nightly 20210215
Yuzu Browser carshes like Oreo.
This device flashed Custom Rom port from Google Play Edition.
So, very similar to AOSP.
