### ISSUE TITLE
Web theme does not work (6.0.0.-nightly Build fb56607d)

### ISSUE THREAD

**Issue by 11mail22** [hazuki0x0/YuzuBrowser#191]
As user of AMOLED i'd like to use a dark mode render. 

With menu "Web theme - force dark mode" the page is rendered dark as expected. But surfing to next site, the render mode is back to normal (e.g. white background).  Also just enter the "Web theme" menu and go back to page, force the "force dark mode" of the actual page.

Second option in "Web theme" the  "dark mode" does not work at all, at least white backgrounds remains white (e.g. google). 

Side question: How to change then menu language to english?

**Comment by ksuuk** [comment]
@hazuki0x0 

Please add either "force to use English" or "language selection" option.

**Comment by hazuki0x0** [comment]
It did not reproduce in my environment. Please add more information (ex. Device environment, settings).

"dark mode" is only enabled if it is set on the site side, so it will be displayed normally (white background) on most sites.

You can change the language in the debug settings in the overflow menu in the settings. However, since this setting is a debug setting, there is no guarantee of normal operation.

**Comment by 11mail22** [comment]
Using Android 9; LG V30

- Web Theme is set to "force dark mode".  
- browse to [https://github.com/hazuki0x0/YuzuBrowser](https://github.com/hazuki0x0/YuzuBrowser) the page background is white
- Enter YUZU settings and leave it by back button (app or android) and page background is rendered dark as expected
- reload page keep background dark, surfing to next page e.g. by clicking issues, background is white. Open/leave settings dark again.

Same can be observed by using "Prefere web theme over force dark mode" in Web Theme menu.
Seem as the setting is not processed at page loading, just triggered by leaving the setting menu
Page mode where night, inverted, grey,... can be configured, is set to normal (honestly I would expect there the force dark mode). Design is set to dark. Changes of these settings does have no impact of the "force dark mode" behaviour.

Hope you can reproduce and make "force darke mode" happen. 

Set language to english in debug menu without any changes, also after restart. Menu language remain in same as after installation.

**Comment by 11mail22** [comment]
Language control works now with build f0faa63 (20210217). Great!

"**Page mode** where night, inverted, grey,..." menu called "**Rendering mode**"
