### ISSUE TITLE
Suggestion: Lowering minimal Android version to KitKat 

### ISSUE THREAD

**Issue by mp107** [hazuki0x0/YuzuBrowser#2]
Welcome,
I would like to suggest lowering down the minimal Android version to API 19 - Android 4.4 KitKat.
It is still one of the most popular versions of the Android OS which still receive security updates from both Google and LineageOS (successor to CyanogenMod).
I have built and run successfully the Yuzu Browser with lowered to API 19 minimal version so it might not need much work with code (I have only changed this value). 

Best regards,
mp107

**Comment by hazuki0x0** [comment]
It has some big problem.
First, biggest problem, Vector drawable isn't support on API 19. AppCompat isn't provide VectorDrawableCompat on getDrawable(). [Google+](https://plus.google.com/+AndroidDevelopers/posts/iTDmFiGrVne)
Second, I already removed the old API code and used the higher API code. I don't want to increase the code to support the older version.

**Comment by mp107** [comment]
I see.
