### ISSUE TITLE
Cannot install versions later than 3.1.3

### ISSUE THREAD

**Issue by firezblade** [hazuki0x0/YuzuBrowser#20]
Hello, 
I am using a samsung galaxy ace 3 lte and custom rom CM12.1 (android 5.1 aka lollipop). The last version of Yuzu browser that I can install and run is 3.1.3. 

Later versions after 3.1.3 either give one of 2 errors :- a) cannot install. b) crashes during installation with errors relating to theme providers. I do not think this relates to the new themes features that was added to Yuzu browser though. 

I suspect this is due to android build tools version 26.0.1 and/or 26.0.2. Will you be kind enough to switch android build tools to version 26.0.3 or 27?

Many thanks.

**Comment by hazuki0x0** [comment]
I released new beta.
Please test it.

**Comment by firezblade** [comment]
Thanks for the prompt response :)
Yes, I can install version 4.0.0 beta3.
