### ISSUE TITLE
Theme creator app not compatible with new theme format

### ISSUE THREAD

**Issue by ertmuirm** [Hazuki0x0/YuzuBrowser#226]
The theme creator app that is publicly available (0.2.2) is not creating themes that are compatible with latest 6.0.2 version of Yuzu Browser. 

Is there an updated Theme Creator app available?

**Comment by ksuuk** [comment]
> The theme creator app that is publicly available (0.2.2) is not creating themes that are compatible with latest 6.0.2 version of Yuzu Browser.

@ertmuirm 
Works fine for me, but when You first make theme, import and use it and then later edit the theme, changes are not reflected immediately, and  every time You must first change active theme to some other, then delete it import and select the recently edited theme again.

**Comment by ertmuirm** [comment]
> > The theme creator app that is publicly available (0.2.2) is not creating themes that are compatible with latest 6.0.2 version of Yuzu Browser.
> 
> @ertmuirm Works fine for me, but when You first make theme, import and use it and then later edit the theme, changes are not reflected immediately, and every time You must first change active theme to some other, then delete it import and select the recently edited theme again.

Thanks. I can't import any theme made using the theme creator app. It creates .json files, but the Yuzu Browser app seems to require .yuzutheme format?

And when I try to import the .json file, it has error message "Manifest not found"

**Comment by ksuuk** [comment]
> Thanks. I can't import any theme made using the theme creator app. It creates .json files, but the Yuzu Browser app seems to require .yuzutheme format?
> 
> And when I try to import the .json file, it has error message "Manifest not found"

@ertmuirm 

Import the entire theme directory, not a single file.

**Comment by ertmuirm** [comment]
> > Thanks. I can't import any theme made using the theme creator app. It creates .json files, but the Yuzu Browser app seems to require .yuzutheme format?
> > And when I try to import the .json file, it has error message "Manifest not found"
> 
> @ertmuirm
> 
> Import the entire theme directory, not a single file.

I get the message "Failed for unknown error" when I try to import directory - perhaps it's sdcard access error in Android 12?

**Comment by ksuuk** [comment]
> I get the message "Failed for unknown error" when I try to import directory - perhaps it's sdcard access error in Android 12?

@ertmuirm 

Works for me, Android 12 > Yuzu > settings > theme management >  import theme > select the theme directory > use this folder > allow yuzu access to this folder > allow.

**Comment by ertmuirm** [comment]
Works for me now. I figured out that my Documents UI app was frozen (since I use another file explorer) and the Yuzu Browser app was trying to use Documents UI specifically so turned an error. Thanks for your help!
