### ISSUE TITLE
Copy of Yuzu Browser?

### ISSUE THREAD

**Issue by SimoLRepo** [Hazuki0x0/YuzuBrowser#227]
Hi, on the Google Play Store on 12/25/2020 an application called <a href="https://play.google.com/store/apps/details?id=jp.ejimax.berrybrowser">Berry Browser</a> was released which apparently has the same interface as <a href="https://play.google.com/store/apps/details?id=jp.hazuki.yuzubrowser">Yuzu browser</a> but <a href="https://berrybrowser.pages.dev/">there doesn't seem to be any source code</a>. Is it a legitimate app or does it violate the Apache License 2.0? Thank you.

**Comment by nymgmail** [comment]
Here is older page explains well. 😁

https://github.com/hazuki0x0/YuzuBrowser/issues/186

----- Original message -----
From: SimoLRepo ***@***.***>
To: hazuki0x0/YuzuBrowser ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hazuki0x0/YuzuBrowser] Copy of Yuzi Browser? (Issue #227)
Date: Monday, April 17, 2023 12:33 PM



Hi, on the Google Play Store on 12/25/2020 an application called Berry Browser <https://play.google.com/store/apps/details?id=jp.ejimax.berrybrowser> was released which apparently has the same interface as Yuzu browser <https://play.google.com/store/apps/details?id=jp.hazuki.yuzubrowser> but there doesn't seem to be any source code <https://berrybrowser.pages.dev/>. Is it a legitimate app or does it violate the Apache License 2.0? Thank you.

**Comment by SimoLRepo** [comment]
> Here is older page explains well. 😁 #186

Thanks for the clarification. I sincerely regret that the development of Yuzu Browser is discontinued. 😕

**Comment by nymgmail** [comment]
Wow, just take a second and read what I'm posting here, I have absolutely loved your browser, I know that from friends berry browser does not have the theme editor and they couldn't get any way for it to work with Barry. 

My wife has done web design coding, twisting programs lol, noodling around on the web for 30 years as a hobby. Back in the eighties she made ten thousand mahjong tile sets and everybody loved them, she never charged for her work she dibbles and dabbles, and she just loves it, and she's made over a thousand yuzu themes... she's written you several times from quite a few different emails hoping that she could find a place.  to put them on the web for people to enjoy, she's had so much fun with your browser and she just couldn't wait for future versions. Yuzu has just gotten better and better and better..

she gave up all her other browsers on her phone..but yuzu . saddens me greatly too. Truly just like we lost a good friend. Best of everything to you. And may God bless.
Hope someone picks it up or forks it and keeps it alive. 
❤❤❤.  




----- Original message -----

**Comment by SimoLRepo** [comment]
> Wow, just take a second and read what I'm posting here, I have absolutely loved your browser, I know that from friends berry browser does not have the theme editor and they couldn't get any way for it to work with Barry.

I want to clarify that I am not the developer of Yuzu Browser. I posted a question because I had doubts about these two browsers. I'm sorry as well the development of Yuzu Browser has been discontinued.

One flaw I found in both browsers is that they incorporate Google Firebase Analytics and Google CrashLytics. Had they been without trackers and had Yuzu Browser been published on F-Droid I would have shown more appreciation.

**Comment by nymgmail** [comment]
A happy Sunday to all I was just hoping that 🔷 the developer might be lurking in the thread and so that's why I posted that. 😁😁

I understand that 🔷you're not the developer😁😁 🔷I'm just hoping somebody will fork it or pick it up or something because it's just wonnnnnnderful.

----- Original message -----
