### ISSUE TITLE
Text reflow on zoom?

### ISSUE THREAD

**Issue by Ioancr** [hazuki0x0/YuzuBrowser#25]
It doesn't automatically rearrange text on display when zooming in or out, even though "text autosizing" is applied in "Layout appearance". I use Samsung S8.

**Comment by hazuki0x0** [comment]
It's a layout algorithm. Not text reflow setting.

Here is the offical description:
>If you were using narrow columns as a way to make a broad spectrum of desktop sites more readable on mobile devices and you aren't able to change the HTML content, the new TEXT_AUTOSIZING algorithm may be a suitable alternative to NARROW_COLUMNS.
>[https://developer.android.com/guide/webapps/migrating.html#Columns](https://developer.android.com/guide/webapps/migrating.html#Columns)
