### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by medwatt** [hazuki0x0/YuzuBrowser#27]
Is there any chance you could implement something like the night mode in Samsung Internet browser. You can download the Samsung Internet browser and see how night mode is implemented. It basically makes the background black, the text white, while retaining the original look of the image.

**Comment by hazuki0x0** [comment]
You can use userscript like https://userstyles.org/styles/31267. The Samsung browser may be use javascript for the night mode(I'm not reseached).

**Comment by medwatt** [comment]
I've just tried adding the userscript you mentioned in your post. It didn't work. Could you please test it in your browser.
