### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by Majara34** [hazuki0x0/YuzuBrowser#3]
First I want to say that I really enjoy this browser. The customization options are amazing. I just have a few suggestions:
1.  I would love to be able to choose what I take a screenshot off( for example maybe just a little bit of the web page.) 
2.  A way to make text urls clickable. 
3. It would be nice to be able to pop out a video I'm watching, and be able to check another tab and multitask.(hope you understand what I mean.) 

Keep up the work with this amazing browser

**Comment by hazuki0x0** [comment]
1. difficult
2. You can use UserScript like [this(I haven't tried).](http://userscripts-mirror.org/scripts/review/36688)
3. Multi window... It is very difficult.
