### ISSUE TITLE
No password save, autofill, export and import function?

### ISSUE THREAD

**Issue by FluffyDiscord** [hazuki0x0/YuzuBrowser#32]
Dear hazuki,
can we expect some sort of system like that? Would be neat to have them, working locally without any cloud service needed - we would export and import the database by ourselves. Or maybe auto backup/restore via Google Drive.

**Comment by hazuki0x0** [comment]
Those system are included in Android 8.0. And I cannot protect private data from crackers. It is not installed as browser function.
