### ISSUE TITLE
Adding Private Tab

### ISSUE THREAD

**Issue by nicd23** [hazuki0x0/YuzuBrowser#33]
Is it possible to add option to open private tab?

**Comment by hazuki0x0** [comment]
It is difficult because of depending on API limitations.

**Comment by nicd23** [comment]
Sorry to hear that, private tab is only feature  missing for me. Can you give more details about API limitations?

**Comment by hazuki0x0** [comment]
The Cookie API can be switched only on an application basis. In 4.1.0, I added Cookie setting in pattern match. However, It can not protect all cookie data. I think private tab should protect all privacy data, so I cannot add it.
