### ISSUE TITLE
Text size issue.

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#35]
Hi,

Settings > Page settings > Text size

0-216 have no effect at all, but 217 > makes text very huge.

Layout algorithm is "Text autosizing", with Normal text size change does have effect.
BTW, What is the purpose of "Text autosizing"? Is is kind of "Force enable zoom"?

**Comment by hazuki0x0** [comment]
This behavior is controlled by WebView. I cannot change it.

According to the reference:
Text autosizing boosts font size of paragraphs based on heuristics to make the text readable when viewing a wide-viewport layout in the overview mode.
