### ISSUE TITLE
Single tab closing.

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#36]
Hi, 

Tab menu, when only one tab is active, I can't close single single. It should be possible to close this tab which opens home page.

**Comment by hazuki0x0** [comment]
It can be changed by setting.

Settings -> Action settings -> Toolbar button settings -> XXX bar button -> Tab list -> xxx -> Tap the options button(gear icon) in Tab list -> Behavior when... -> chose what you want

**Comment by ksuuk** [comment]
Actually I can't choose what I wan't, there is only four hardcoded options:
None
New tab
Finish
Finish with alert

**Comment by mp107** [comment]
@ksuuk 
Do you meant setting such behaviour for "X" button visible on the tab thumbnails or for a custom button on some toolbar?

**Comment by ksuuk** [comment]
I mean behaviour for "X" button visible on the tab thumbnail.

**Comment by mp107** [comment]
I understand.
So, there might be currently no way to achieve that.
At least I do not know any.

@hazuki0x0 
Unfortunately, the method you have described does not refer to the ksuuk's issue.
There is no action after clicking on the "X" button placed on the tab thumbnail with only one tab open. The back/forward history seems to be intact so it looks like the tab has not being closed.

**Comment by ksuuk** [comment]
Please add also button to close all tabs, as right now there is only hardcoded + button, at right, for new tab.

**Comment by Rikk** [comment]
I can't see the X button (close tab) inside any tab and can't find an option to add it; I know I can add a "close tab" button to any toolbar, but not inside each tab.

**Comment by ksuuk** [comment]
@Rikk 

You are looking top, but I was talking about bottom tab bar:

![screenshot_2](https://user-images.githubusercontent.com/26193002/38853401-c8fbf68e-4225-11e8-912b-510d01599774.png)

**Comment by Rikk** [comment]
@ksuuk sorry, I thought it was related to the subject of this thread and that my question could fit here instead of creating a new issue.
