### ISSUE TITLE
Bookmarks, sort and layout issue.

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#37]
Hi,

1) I imported bookmarks & folders from other browser, but now bookmarks and folders are listed by name and I can't move folders to top with one command, I must select "move up", and folder moves up by one position only. But when when I add new folder, I can select "Add to top". Please add option, that any bookmark folder can add to top with one click and option that folders are always listed above bookmarks.

2) Sorting is made by what? Sorting should have options to choose, for example by frequency, by date created, by name etc.

3) Icons in the bookmark and history menu are too big. They should be sized not by line but text height.

**Comment by hazuki0x0** [comment]
1. You can tap the sort button on action bar and long press the bookmark item to drag.  
Sorry, the option(Add to top) is removed by the critical bug.

2. It is as explained above. This browser has only url and name data...

3. I will adjust the size.
