### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by bastadur** [hazuki0x0/YuzuBrowser#4]
- When clicking Private tab from menu it should show some kind of notice that it's turned on/off.
- Add an option to show history entries as suggestion in the url bar. 
- Closing the last tab (when the option not to close the browser is on) should redirect to the homepage/speeddial. Now it's not possible to do that as far as I can tell.

👍

**Comment by hazuki0x0** [comment]
1 2 i'll consider those.
3. You can use [Close all] action in [Action on no histories].

**Comment by brinbili** [comment]
Oh, you're right about the number three. So many options, one can easily lose track. 😅

Thanks.

**Comment by hazuki0x0** [comment]
Add to v3.3
