### ISSUE TITLE
 No downloads history option or selection.

### ISSUE THREAD

**Issue by ksuuk** [hazuki0x0/YuzuBrowser#42]
Yazu is missing the downloads history option/selection, so when downloads are done or failed then Yazu doesn't know it.

Also what in settings > browser settings is  twice listed "download directory", first allows to specify the download path but second opens the phone storage.

**Comment by hazuki0x0** [comment]
You can use "Download list" action to check downloads state.

"download directory" bug is fixed in 4.1.0-beta4.

**Comment by ksuuk** [comment]
Sorry, where is the "Download list" action?

**Comment by hazuki0x0** [comment]
By default it is in options button '︙'.

You can add the action if you cannot find.
Open settings -> Action settings -> Options menu settings -> Tap '+' button at bottom right -> check "download list" -> Tap OK

However, '+' button in options menu is not work in beta5...
I'll fix it.

**Comment by ksuuk** [comment]
Ok, got it, but seems download list have no option to delete all, like normal history have, also timestamp is missing. And clicking the file does nothing. Maybe download list should use same style, options, etc like history is using?
