### ISSUE TITLE
Unable to play music from yuzu browser download list using Odyssey music player

### ISSUE THREAD

**Issue by kodeblacc** [hazuki0x0/YuzuBrowser#50]
#### Expected behavior
I expected that if I downloaded a music I could play the music from the download list of the app.

#### Actual behavior
When I play a downloaded music with odyssey music player it doesn't play.

#### How to reproduce
- download both apps yuzu browser and odyssey music player
- launch both apps and allow all permissions
- on the browser download a music file
- opt to play the music from the download list with odyssey music player as the preferred choice to play it
- it doesn't play it

* Device:  Infinix Note 4
* Operating system: Android 8.1
* Software Version: Yuzu browser(4.0.4)
Odyssey music player(v 1.1.13)

#### Recording Of The Bug
https://vimeo.com/261781825

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/unable-to-play-music-from-yuzu-browser-download-list-using-odyssey-music-player">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hazuki0x0** [comment]
Can you play music in that way using other music player?

**Comment by kodeblacc** [comment]
I didn't try any other player.
I mostly use odyssey music player

**Comment by hazuki0x0** [comment]
If you can play with other players, there is a possibility of a bug in odyssey music player.

**Comment by kodeblacc** [comment]
Let me try with other players I have

**Comment by kodeblacc** [comment]
I tried with some other players and it didn't work..
Should I report them as bugs or 1 fix would work for all?

**Comment by hazuki0x0** [comment]
Thank you for trying.
It seems to be a bug in this browser.

**Comment by kodeblacc** [comment]
Okay so I shouldn't bother about reporting other music players the bug
affects?

**Comment by hazuki0x0** [comment]
Yes.
You can use the beta version (4.1.0) with the downloader changed significantly. Please check it if you like.

**Comment by kodeblacc** [comment]
How can I locate the beta version

**Comment by kodeblacc** [comment]
I'm checking it out now

**Comment by kodeblacc** [comment]
The beta version is worse.
It says acceptable application not found

**Comment by hazuki0x0** [comment]
"application not found" bug is fixed.

**Comment by kodeblacc** [comment]
In a new version?

On Apr 15, 2018 12:02 PM, "Hazuki" <notifications@github.com> wrote:

"application not found" bug is fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hazuki0x0/YuzuBrowser/issues/50#issuecomment-381397649>,
or mute the thread

**Comment by hazuki0x0** [comment]
Yes. In 4.1.0

**Comment by kodeblacc** [comment]
Alright thanks
