### ISSUE TITLE
Case when we can't zoom with double-tap+drag and Pull To Refresh is enabled

### ISSUE THREAD

**Issue by Rikk** [hazuki0x0/YuzuBrowser#67]
With Pull To Refresh option enabled, using a double-tap+drag gesture to zoom in/out doesn't work when you are on the **top** of a page, because it will trigger the Pull to Refresh gesture instead.

Btw, double-tap+drag gesture does not trigger zoom when the page is not scrollable with current zoom.

**Comment by Rikk** [comment]
Very good, thanks!

**Comment by hazuki0x0** [comment]
The behavior may be default of the WebView. I tried it with other browsers and did the same behavior.
Please tell me the URL if you find a page to do other actions in other browser.
