### ISSUE TITLE
Blank Content Settings

### ISSUE THREAD

**Issue by Rikk** [hazuki0x0/YuzuBrowser#69]
What options should exist inside Privacy Settings -> Content Settings?

![blank content settings](https://user-images.githubusercontent.com/2916485/39395791-6787959c-4ab9-11e8-8e3b-5af0b126e7f9.png)

**Comment by hazuki0x0** [comment]
This settings is permission list of the each website(ex. mic, camera). It will be displayed, if you choose to allow/disallow of the permissions.

**Comment by Rikk** [comment]
Ok thanks
