### ISSUE TITLE
Going back to home screen or speed dial menu takes a few seconds

### ISSUE THREAD

**Issue by medwatt** [hazuki0x0/YuzuBrowser#7]
If I have a website loaded on a tab and want to go to the home screen or speed dial menu, it takes a couple of seconds to load it as if it's loading a web page from some remote web server. This should happen instantaneously.

**Comment by hazuki0x0** [comment]
I know this issue. However, those connection requests are not returned from webview. May be a Chromium's bug.
I wanna change browser base code and speed up, but I do not have time to make major changes now.

**Comment by hazuki0x0** [comment]
Improve c2197579b14797da38ded081c4b4569875ffcddc
