### ISSUE TITLE
There is the option for detailed logging, but no place to view. 

### ISSUE THREAD

**Issue by Avrution** [hazuki0x0/YuzuBrowser#72]
LOVE the browser and have switched over as my main, but it crashes a ton.  

It would be great to see a record of what might be the crash reason so it could be avoided or any helpful logging details.  

Would also love to support a paid version or even just donate towards development.

**Comment by hazuki0x0** [comment]
The crash log is saved in` /sdcard/Android/data/jp.hazuki.yuzubrowser/files/error_log`.

I'm considering making a donation way now.
