### ISSUE TITLE
Speeddial shouldn't pull from internet on load

### ISSUE THREAD

**Issue by Avrution** [hazuki0x0/YuzuBrowser#76]
Speeddial is my default homepage and sometimes when loading a new tab it takes up to a minute for the (35) icons to load. 

I don't know if it is trying to refresh the icons, but with internet disabled everything loads instantly.  

Internet activity monitor shows traffic both ways, with most being download.

**Comment by hazuki0x0** [comment]
Speed dial is not connect any server when opening. However, WebView may be connecting somewhere.

I'm going to investigate.

**Comment by Avrution** [comment]
I just checked and opening the app to the speeddial page opens 69 connections.  Browsing to just google after that still leaves open 32 connections.  Might explain why the performance of the browser bogs down so much once i open 3 or more tabs.
