### ISSUE TITLE
Suggestion - Do not auto reload tabs on app focus

### ISSUE THREAD

**Issue by Avrution** [hazuki0x0/YuzuBrowser#79]
Minor issue, but it is rather annoying that all tabs are refreshed when Yuzu becomes the focus app after using something else.

For example, I switch over to check my email and then move back to Yuzu, all the tabs refresh, which can take quite a while with a lot open.  The same applied for using on a tablet with wifi off with screen off - turn on tablet and open Yuzu back up and it tries to refresh before the wifi connection picks back up, leading to a bunch of no connection pages.

**Comment by hazuki0x0** [comment]
The application is likely to be terminated by the OS, so I cannot fix it. 
The solution is to make more memory available.
