### ISSUE TITLE
Spectre / Meltdown threat mitigation?

### ISSUE THREAD

**Issue by mgraham** [hazuki0x0/YuzuBrowser#81]
So this may be a stupid question, but does Yuzu have anything like Chrome's strict-site-isolation?

`chrome://flags/#enable-site-per-process`

I'm on an Android device with an A57 core (which is vulnerable), but which will probably never get a security update.

**Comment by hazuki0x0** [comment]
There is no WebView info on that function, so Yuzu can not do anything. One thing I can say for sure is to keep WebView/Chrome up-to-date.

**Comment by mgraham** [comment]
Ok, thank you!
