### ISSUE TITLE
Feature Suggestions(機能提案)

### ISSUE THREAD

**Issue by Rintan** [hazuki0x0/YuzuBrowser#97]
現在、いくつかのブラウザではYouTubeやniconicoなどのサイトで画面オフバックグラウンド再生を行えるような機能が追加されており、需要が高いと思われます。Webviewの仕組みやバックグラウンドプロセスのことはよく分からないので、実装については不明な点が多いですが、ご検討のほどよろしくお願いします。

**Comment by quroe** [comment]
Issueを見ていて目に入ったので去年の物ですが
バックグラウンド再生の機能について、YouTubeでやられると困るのか怒られてストアから削除されます
最近だとブラウザにおいてはKiwi Browserもこれに当てはまり非公開化→機能削除をして更新という形になりました
ストアアプリとしても公開をしているので実装コストを抜きに考えても難しいと思います
Close をして wontfix Labelsをつけて良いのでは？ @hazuki0x0

**Comment by Rintan** [comment]
> Issueを見ていて目に入ったので去年の物ですが
> バックグラウンド再生の機能について、YouTubeでやられると困るのか怒られてストアから削除されます
> 最近だとブラウザにおいてはKiwi Browserもこれに当てはまり非公開化→機能削除をして更新という形になりました
> ストアアプリとしても公開をしているので実装コストを抜きに考えても難しいと思います
> Close をして wontfix Labelsをつけて良いのでは？ @hazuki0x0

確かにこの投稿をした当時とはPlayのポリシーも変わりました。なので、今後の機能追加には不可能ことでこのissueを閉めさせていただきます。(閉め忘れてました)
